### ISSUE TITLE
Add a `--column <csv-column-name>` option to `sendBatch`

### ISSUE THREAD

**Issue by Sladuca** [CMU-Blockchain-Group/eth-cli#3]
Add a new `--column` option to `sendBatch` that allows the user to specify which column of the given CSV contains the addresses to send to.

If the option is not given, default to `"Ethereum Address"`. If it is given, use that column and display an error message if the given column name DNE in the CSV.

**Comment by BozeBro** [comment]
I think I added the column feature properly. Check pull request
